apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  podMonitorSelector: {}
  ruleSelector: 
    matchLabels:
      name: prometheusrule
      role: promrul
  resources:
    requests:
      memory: 400Mi

