apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./bases/grafana-agent
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
