apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  healthChecks:
    - kind: CustomResourceDefinition
      name: certificaterequests.cert-manager.io
    - kind: CustomResourceDefinition
      name: certificates.cert-manager.io
  interval: 1m0s
  path: ./bases/cert-manager-crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s

