apiVersion: v1
kind: ConfigMap
metadata:
  name: yace-v1
  namespace: yace
data:
  config.yml: |
    discovery:
      jobs:
      - regions: 
          - us-east-1
        type: elb
        enableMetricData: true
        metrics:
          - name: HealthyHostCount
            statistics:
            - Average
            period: 300
            length: 600
---




