apiVersion: v1
kind: Service
metadata:
  name: yace
  namespace: yace
  labels:
    name: yace
    app: yace
  annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "5000"
spec:
  selector: 
    app: yace
  type: NodePort  
  ports:
    - port: 5000
      targetPort: 5000
      name: yace-metrics