---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/Muthuraj647/fleet-infra/bases/grafana-agent
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 5m0s
  path: ../bases/grafana-agent
  prune: true
  sourceRef:
    kind: GitRepository
    name: grafana
  targetNamespace: default

